version: "3"

volumes:
  db-data:
    external: false

services:
  db:
    image: mysql/mysql-server:latest
    env_file: .env
    volumes:
      - ./files/mysql/:/docker-entrypoint-initdb.d/

  app:
    build: .
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db

