development:
  adapter: <%= ENV.fetch("SNOTE_DB_ADAPTER") %>
  host: <%= ENV.fetch("SNOTE_DB_HOST") %>
  database: <%= ENV.fetch("SNOTE_DB_DATABASE") %>
  username: <%= ENV.fetch("SNOTE_DB_USER") %>
  password: <%= ENV.fetch("SNOTE_DB_PASSWORD") %>
  encoding: <%= ENV.fetch("SNOTE_DB_ENCODING") %>
  pool: 5
  timeout: 5000

production:
  adapter: <%= ENV.fetch("SNOTE_DB_ADAPTER") %>
  host: <%= ENV.fetch("SNOTE_DB_HOST") %>
  database: <%= ENV.fetch("SNOTE_DB_DATABASE") %>
  username: <%= ENV.fetch("SNOTE_DB_USER") %>
  password: <%= ENV.fetch("SNOTE_DB_PASSWORD") %>
  encoding: <%= ENV.fetch("SNOTE_DB_ENCODING") %>
  pool: 5
  timeout: 5000
